import { Achievement, EducationalActivityProgress, RankTierInfo } from './types';

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'conhecedor_direitos',
    title: 'Calouro Anti-Treta',
    subtitle: 'O primeiro passo para uma escola sem zueira pesada',
    description: 'Conclua seu primeiro quiz educativo sobre prevenção ao bullying e convivência escolar.',
    unlockedDescription: 'Parabéns! Você deu o pontapé inicial na cultura de paz. O primeiro passo foi dado com honra!',
    funnyQuote: '‘Zueira que machuca não é brincadeira, é falta de roteiro bom.’',
    funnySticker: '🎓',
    category: 'sabedoria',
    tier: 'bronze',
    iconType: 'trophy',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 1,
    progressUnit: 'quiz concluído',
    requirementHint: 'Conclua qualquer 1 quiz na aba "Quiz Anti-Bullying".'
  },
  {
    id: 'aliado_escola_segura',
    title: 'Trio Parada Firme da Paz',
    subtitle: 'Três quizzes no bolso e tolerância zero com covardia',
    description: 'Amplie seus conhecimentos completando 3 quizzes educativos sobre respeito e segurança.',
    unlockedDescription: 'Incrível! Três quizzes finalizados. Você já pode dar aula de bom senso no intervalo!',
    funnyQuote: '‘Três vitórias seguidas. Nem o Wi-Fi da escola é tão estável quanto sua determinação.’',
    funnySticker: '🛡️',
    category: 'sabedoria',
    tier: 'prata',
    iconType: 'shield',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 3,
    progressUnit: 'quizzes concluídos',
    requirementHint: 'Conclua 3 quizzes diferentes na área "Quiz Anti-Bullying".'
  },
  {
    id: 'especialista_respeito',
    title: 'Cérebro Galáctico do Respeito',
    subtitle: 'Neurônios brilhando mais que a tela do celular no escuro',
    description: 'Demonstre domínio e alcance pelo menos 80% de aproveitamento em 3 quizzes educativos.',
    unlockedDescription: 'Uau! Aproveitamento de elite (≥80%) em 3 quizzes. Seus argumentos contra o preconceito são imbatíveis!',
    funnyQuote: '‘QI de empatia acima de 9.000! Albert Einstein ficaria orgulhoso dessa mente brilhante.’',
    funnySticker: '🧠',
    category: 'sabedoria',
    tier: 'ouro',
    iconType: 'sparkles',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 3,
    progressUnit: 'quizzes com ≥ 80%',
    requirementHint: 'Acerte pelo menos 4 de 5 perguntas (80%) em 3 quizzes educativos.'
  },
  {
    id: 'protetor_comunidade',
    title: 'Gabaritador Lendário de Bom Senso',
    subtitle: 'Zerou todos os 5 quizzes da jornada educativa',
    description: 'Conclua todos os 5 quizzes disponíveis na jornada educativa do Sentinela Escolar.',
    unlockedDescription: 'Jornada zerada com sucesso! Você completou todos os quizzes. O Ministério do Respeito te aplaude de pé!',
    funnyQuote: '‘Platinou o quiz! Agora você tem imunidade diplomática contra fofocas e picuinhas.’',
    funnySticker: '👑',
    category: 'sabedoria',
    tier: 'lendario',
    iconType: 'crown',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 5,
    progressUnit: 'quizzes concluídos',
    requirementHint: 'Complete todos os 5 quizzes educativos disponíveis na plataforma.'
  },
  {
    id: 'gabarito_perfeito',
    title: 'Oráculo do 100% Sem Chute',
    subtitle: 'Acertou 5 de 5 perguntas de primeira. Aqui é pura sabedoria!',
    description: 'Alcance pontuação máxima perfeita (100%) em qualquer um dos quizzes educativos.',
    unlockedDescription: 'Perfeição pura! Você acertou todas as perguntas de um quiz sem errar uma única vírgula.',
    funnyQuote: '‘Não foi uni-duni-tê: foi estudo, empatia e mira laser na alternativa certa!’',
    funnySticker: '🎯',
    category: 'sabedoria',
    tier: 'ouro',
    iconType: 'target',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 1,
    progressUnit: 'quiz com 100%',
    requirementHint: 'Acerte 5 de 5 perguntas (100%) em qualquer quiz educativo.'
  },
  {
    id: 'speedrunner_sabedoria',
    title: 'Detetive Cibernético Anti-Fake',
    subtitle: 'Firewall moral ativado contra o cyberbullying',
    description: 'Conclua o Quiz de Cyberbullying e Segurança Digital com aproveitamento igual ou superior a 80%.',
    unlockedDescription: 'Mestre da internet segura! Você sabe como proteger provas digitais e barrar o ódio online.',
    funnyQuote: '‘Nem os trolls da web mais experientes conseguem passar pelo seu escudo de bom senso.’',
    funnySticker: '🕵️‍♂️',
    category: 'detetive',
    tier: 'prata',
    iconType: 'bot',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 1,
    progressUnit: 'cyber quiz concluído',
    requirementHint: 'Conclua o quiz "Cyberbullying & Segurança Digital" com 80%+ de acerto.'
  },
  {
    id: 'enciclopedia_viva',
    title: 'Maratonista de Neurônios',
    subtitle: 'Respondeu 20 perguntas em quizzes educativos',
    description: 'Demonstre consistência acumulando pelo menos 20 respostas respondidas nos quizzes.',
    unlockedDescription: 'Que fôlego intelectual! Você já respondeu mais de 20 questões sobre convivência ética e segurança.',
    funnyQuote: '‘Mais focado que estudante em semana de prova e com coração 100% no lugar certo.’',
    funnySticker: '🏃‍♂️',
    category: 'sabedoria',
    tier: 'ouro',
    iconType: 'zap',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 20,
    progressUnit: 'questões respondidas',
    requirementHint: 'Responda a pelo menos 20 questões no total nos quizzes educativos.'
  },
  {
    id: 'explorador_matriz',
    title: 'Curioso Nível Hard: 7 em 1',
    subtitle: 'Explorou todas as 7 categorias da Matriz de Bullying',
    description: 'Estude todos os 7 tipos de bullying (verbal, físico, cyber, moral, social, material e sexual).',
    unlockedDescription: 'Explorador completo! Você conheceu os detalhes, sinais e formas de reação de todas as 7 categorias.',
    funnyQuote: '‘Você manja mais de prevenção escolar do que o fiscal de corredor mais antigo!’',
    funnySticker: '🔍',
    category: 'detetive',
    tier: 'prata',
    iconType: 'compass',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 7,
    progressUnit: 'categorias exploradas',
    requirementHint: 'Clique e explore todas as 7 abas na Matriz dos 7 Tipos de Bullying.'
  },
  {
    id: 'advogado_do_bem',
    title: 'Doutor em Não-Vacilo (Vade Mecum Escolar)',
    subtitle: 'Leu a Lei 13.185/2015 e o Artigo 146-A da Lei 14.811',
    description: 'Acesse o módulo de Legislação e conheça seus direitos e a proteção legal contra a intimidação.',
    unlockedDescription: 'Conhecedor das Leis! Se alguém tentar intimidar, você cita a Lei 14.811 com postura de respeito.',
    funnyQuote: '‘Código Penal na ponta da língua e empatia no coração: ninguém te passa a perna.’',
    funnySticker: '⚖️',
    category: 'detetive',
    tier: 'bronze',
    iconType: 'scale',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 1,
    progressUnit: 'módulo de leis',
    requirementHint: 'Leia o módulo "Leis e Proteção Legal" e clique em "Marcar como Lido".'
  },
  {
    id: 'coracao_de_ouro',
    title: 'Embaixador da Empatia Master',
    subtitle: 'Superpoder oficial: nunca deixar ninguém sozinho no recreio',
    description: 'Conclua a leitura e reflexão do Módulo de Respeito, Empatia e Convivência Escolar.',
    unlockedDescription: 'Coração gigante! Você compreendeu a importância de acolher colegas e ser uma testemunha ativa do bem.',
    funnyQuote: '‘Pequenos gestos de gentileza salvam o dia de alguém sem você nem perceber.’',
    funnySticker: '💖',
    category: 'empatia',
    tier: 'bronze',
    iconType: 'handshake',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 1,
    progressUnit: 'módulo de respeito',
    requirementHint: 'Clique em "Marcar como Lido e Compreendido" no banner de Respeito e Empatia.'
  },
  {
    id: 'campeao_inclusao',
    title: 'Radar Anti-Exclusão Social',
    subtitle: 'Para você, todo mundo tem lugar garantido no time',
    description: 'Conclua o Quiz de Empatia e Convivência Escolar com aproveitamento excelente (≥80%).',
    unlockedDescription: 'Craque do acolhimento! Você sabe exatamente como transformar panelinhas tóxicas em pontes de amizade.',
    funnyQuote: '‘Se a vida fosse um jogo cooperativo, você seria aquele player que revive o time inteiro!’',
    funnySticker: '🤝',
    category: 'empatia',
    tier: 'prata',
    iconType: 'heart',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 1,
    progressUnit: 'quiz de empatia',
    requirementHint: 'Conclua o quiz "Empatia & Convivência" com 80%+ de acertos.'
  },
  {
    id: 'mente_tranquila',
    title: 'Monge Zen Anti-Estresse',
    subtitle: 'Inspirou 4, segurou 7, soltou 8. O caos sumiu!',
    description: 'Realize uma sessão de respiração guiada 4-7-8 no botão "Acalmar" ou no Apoio Emocional.',
    unlockedDescription: 'Paz restaurada! Você praticou a técnica comprovada de descompressão e oxigenou a mente.',
    funnyQuote: '‘Respirou fundo e o estresse evaporou igual água em frigideira quente. Namastê!’',
    funnySticker: '🧘‍♂️',
    category: 'zen',
    tier: 'bronze',
    iconType: 'wind',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 1,
    progressUnit: 'sessão de respiração',
    requirementHint: 'Clique no botão "Acalmar" (no topo) ou use o exercício no Apoio Emocional.'
  },
  {
    id: 'mestre_zen',
    title: 'Pulmão de Aço da Serenidade',
    subtitle: 'Três sessões de descompressão concluídas com maestria',
    description: 'Complete 3 sessões completas de respiração e relaxamento para manter a tranquilidade.',
    unlockedDescription: 'Nível mestre de serenidade! Nem prova surpresa com chamada oral abala a sua paz interior.',
    funnyQuote: '‘Sua calma interior é tão sólida que até monges tibetanos pediriam dicas de meditação.’',
    funnySticker: '🫁',
    category: 'zen',
    tier: 'prata',
    iconType: 'wind',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 3,
    progressUnit: 'sessões de calma',
    requirementHint: 'Pratique 3 sessões do exercício de respiração 4-7-8.'
  },
  {
    id: 'desabafo_seguro',
    title: 'Coração Leve, Mente Clara',
    subtitle: 'Acolhimento com privacidade e escuta atenta',
    description: 'Abra a Central de Apoio Emocional e converse com o assistente confidencial de apoio.',
    unlockedDescription: 'Conversar alivia a alma! Você acessou um espaço seguro para organizar ideias e emoções.',
    funnyQuote: '‘Guardar tudo pra si é pesado demais. Desabafar com segurança é pura sabedoria.’',
    funnySticker: '💬',
    category: 'empatia',
    tier: 'bronze',
    iconType: 'smile',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 1,
    progressUnit: 'conversa de apoio',
    requirementHint: 'Envie uma mensagem ou abra o chat na aba "Apoio Emocional".'
  },
  {
    id: 'guardiao_digital',
    title: 'Agente Secreto do Protocolo',
    subtitle: 'Segurança máxima: chave de acompanhamento 100% anônima',
    description: 'Consulte o andamento de um protocolo confidencial ou copie seu código com segurança.',
    unlockedDescription: 'Agente da transparência! Você aprendeu a acompanhar desfechos com total privacidade.',
    funnyQuote: '‘Nem a NASA tem um código tão bem guardado quanto o seu protocolo seguro!’',
    funnySticker: '🔐',
    category: 'escudo',
    tier: 'prata',
    iconType: 'eye',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 1,
    progressUnit: 'consulta realizada',
    requirementHint: 'Consulte um protocolo na aba "Acompanhar Protocolo".'
  },
  {
    id: 'radar_antizueira',
    title: 'Escudo Guardião Ativado',
    subtitle: 'Atuando com responsabilidade para uma escola melhor',
    description: 'Envie ou consulte um relato seguro contra o bullying, ajudando a proteger o ambiente escolar.',
    unlockedDescription: 'Protetor em ação! Sua atitude cidadã ajuda a quebrar o ciclo de silêncio e impunidade.',
    funnyQuote: '‘Herói da vida real não usa capa, usa bom senso e canais éticos de proteção.’',
    funnySticker: '🛡️',
    category: 'escudo',
    tier: 'bronze',
    iconType: 'shield',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 1,
    progressUnit: 'ação de proteção',
    requirementHint: 'Envie um relato responsável ou consulte seu código anônimo.'
  },
  {
    id: 'sentinela_noturno',
    title: 'Sentinela Noturno da Paz',
    subtitle: 'A cultura do respeito não tira folga nem quando o sol se põe',
    description: 'Estude ou acesse a plataforma Sentinela Escolar para fortalecer a convivência pacífica.',
    unlockedDescription: 'Dedicação comprovada! Você está sempre pronto para aprender e disseminar o respeito.',
    funnyQuote: '‘A coruja da sabedoria passou por aqui e deixou um distintivo especial pra você!’',
    funnySticker: '🦉',
    category: 'escudo',
    tier: 'bronze',
    iconType: 'award',
    isUnlocked: false,
    isSecret: true,
    currentProgress: 1,
    maxProgress: 1,
    progressUnit: 'acesso à plataforma',
    requirementHint: 'Explore os recursos do Sentinela Escolar.'
  },
  {
    id: 'primeiro_passo_simulacao',
    title: 'Protagonista da Empatia',
    subtitle: 'Primeiro Passo nas Simulações Interativas',
    description: 'Conclua sua primeira simulação interativa de tomada de decisões no cotidiano escolar.',
    unlockedDescription: 'Sensacional! Você viveu sua primeira história interativa e tomou decisões conscientes na prática.',
    funnyQuote: '‘Você não apenas assiste ao filme: você muda o roteiro para um final muito mais justo!’',
    funnySticker: '🎭',
    category: 'sabedoria',
    tier: 'bronze',
    iconType: 'sparkles',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 1,
    progressUnit: 'simulação concluída',
    requirementHint: 'Conclua qualquer 1 simulação interativa na aba "Simulações 🎭".'
  },
  {
    id: 'olhar_empatico',
    title: 'Coração de Escudo & Acolhimento',
    subtitle: 'Olhar Empático nas decisões do dia a dia',
    description: 'Escolha ações deliberadas de apoio, escuta ativa e acolhimento a colegas nas simulações.',
    unlockedDescription: 'Que sensibilidade brilhante! Suas escolhas acolheram colegas vulneráveis com respeito e empatia.',
    funnyQuote: '‘Com esse nível de empatia, até o Wi-Fi da escola se conecta melhor ao seu bom coração!’',
    funnySticker: '🤝',
    category: 'empatia',
    tier: 'prata',
    iconType: 'heart',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 3,
    progressUnit: 'escolhas de empatia',
    requirementHint: 'Faça 3 escolhas empáticas de apoio nas simulações interativas.'
  },
  {
    id: 'decisao_segura',
    title: 'Estrategista da Proteção',
    subtitle: 'Decisões Seguras que evitam riscos e conflitos',
    description: 'Complete 3 simulações alcançando finais seguros e com apoio institucional de adultos responsáveis.',
    unlockedDescription: 'Inteligência pura! Você provou que proteger a escola significa buscar ajuda com segurança e sem violência.',
    funnyQuote: '‘Segurança em primeiro lugar: você pensa rápido e aciona os apoios certos como um verdadeiro mestre.’',
    funnySticker: '🛡️',
    category: 'escudo',
    tier: 'ouro',
    iconType: 'shield',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 3,
    progressUnit: 'simulações seguras',
    requirementHint: 'Conclua 3 simulações com decisões voltadas à segurança e mediação segura.'
  },
  {
    id: 'pensador_estrategico',
    title: 'Mestre do Multiverso Escolar',
    subtitle: 'Pensador Estratégico e explorador de caminhos',
    description: 'Explore diferentes caminhos e descubra finais variados em uma mesma simulação interativa.',
    unlockedDescription: 'Curiosidade de elite! Você rejogou e descobriu caminhos alternativos para entender todas as consequências.',
    funnyQuote: '‘Doutor Estranho ficaria com inveja da sua habilidade de prever e testar todas as ramificações!’',
    funnySticker: '🧠',
    category: 'detetive',
    tier: 'ouro',
    iconType: 'compass',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 2,
    progressUnit: 'finais em 1 cenário',
    requirementHint: 'Descubra pelo menos 2 finais/caminhos diferentes em uma mesma simulação.'
  },
  {
    id: 'guardiao_comunidade_sim',
    title: 'Guardião Supremo da Convivência',
    subtitle: 'Completou todas as 10 simulações interativas',
    description: 'Vivencie e conclua todas as 10 situações fictícias disponíveis no Sentinela Escolar.',
    unlockedDescription: 'Platina lendária! Você dominou todas as 10 simulações interativas e é uma referência de cultura de paz.',
    funnyQuote: '‘Você platinou o laboratório de decisões éticas! O universo escolar está muito mais seguro com você.’',
    funnySticker: '🌟',
    category: 'sabedoria',
    tier: 'lendario',
    iconType: 'crown',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 10,
    progressUnit: 'simulações zeradas',
    requirementHint: 'Complete todas as 10 simulações interativas disponíveis.'
  },
  {
    id: 'colecionador_supremo',
    title: 'Lorde Supremo dos Distintivos',
    subtitle: 'Desbloqueou 10 ou mais conquistas na plataforma',
    description: 'Demonstre dedicação máxima desbloqueando pelo menos 10 conquistas educativas no Sentinela.',
    unlockedDescription: 'Lenda absoluta! Você atingiu a marca de 10 conquistas. Sua dedicação à cultura de paz é exemplar!',
    funnyQuote: '‘Você praticamente platinou o Sentinela Escolar! A diretoria deveria te dar uma medalha de ouro.’',
    funnySticker: '🏆',
    category: 'sabedoria',
    tier: 'lendario',
    iconType: 'trophy',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 10,
    progressUnit: 'conquistas desbloqueadas',
    requirementHint: 'Desbloqueie pelo menos 10 conquistas diferentes no sistema.'
  },
  // =========================================================================
  // 🌟 NOVAS CONQUISTAS AVANÇADAS, COMBINADAS E LENDÁRIAS (Progressão de Dificuldade)
  // =========================================================================
  {
    id: 'veterano_questoes',
    title: 'Ás da Sabedoria Escolar',
    subtitle: 'Respondeu 40 ou mais questões em quizzes educativos',
    description: 'Demonstre perseverança intelectual acumulando pelo menos 40 respostas respondidas nos quizzes de prevenção ao bullying.',
    unlockedDescription: 'Resiliência exemplar! Com 40 questões respondidas, sua base de conhecimento contra a intimidação escolar é sólida.',
    funnyQuote: '‘Quem estuda a convivência pacífica transforma o ambiente escolar com sabedoria e empatia.’',
    funnySticker: '⚡',
    category: 'sabedoria',
    tier: 'prata',
    iconType: 'zap',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 40,
    progressUnit: 'questões respondidas',
    requirementHint: 'Responda a pelo menos 40 questões no total nos quizzes educativos.'
  },
  {
    id: 'oraculo_cinco_estrelas',
    title: 'Mestre da Precisão Total',
    subtitle: 'Alcançou nota 100% em pelo menos 3 quizzes diferentes',
    description: 'Acerte todas as perguntas (100% de precisão) em 3 quizzes educativos distintos na plataforma.',
    unlockedDescription: 'Pontaria impecável! Três gabaritos perfeitos com 100% de acerto. Seus argumentos contra o bullying são irrefutáveis!',
    funnyQuote: '‘Três notas máximas sem pestanejar. A prova do respeito foi gabaritada com louvor!’',
    funnySticker: '🎯',
    category: 'sabedoria',
    tier: 'ouro',
    iconType: 'target',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 3,
    progressUnit: 'quizzes com 100%',
    requirementHint: 'Acerte 100% de questões em 3 quizzes educativos distintos.'
  },
  {
    id: 'explorador_total_matriz',
    title: 'Especialista em Tipologia de Bullying',
    subtitle: 'Explorou todas as 8 categorias detalhadas na Matriz',
    description: 'Estude a fundo todos os 8 tipos de bullying na Matriz Educativa (verbal, físico, moral, psicológico, social, material, cyberbullying e sexual).',
    unlockedDescription: 'Mapeamento completo! Você conhece a fundo as 8 manifestações de agressão e sabe como agir preventivamente em cada uma.',
    funnyQuote: '‘Diagnóstico preciso: você sabe identificar o problema pela raiz antes que ele cresça.’',
    funnySticker: '📚',
    category: 'detetive',
    tier: 'prata',
    iconType: 'book',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 8,
    progressUnit: 'categorias analisadas',
    requirementHint: 'Explore todas as 8 abas de tipos de bullying na área educativa.'
  },
  {
    id: 'combo_iniciante_sentinela',
    title: 'Guardião Multifacetado',
    subtitle: 'Concluiu Leis + Respeito + 2 Quizzes + 2 Simulações',
    description: 'Demonstre equilíbrio interdisciplinar completando a leitura das Leis, do Módulo de Respeito, 2 quizzes e 2 simulações.',
    unlockedDescription: 'Visão 360º de proteção! Você combinou fundamentação legal, empatia e tomada de decisão na prática.',
    funnyQuote: '‘Teoria e prática alinhadas: você entende a lei, sente a dor do colega e toma a atitude certa!’',
    funnySticker: '🛡️',
    category: 'escudo',
    tier: 'prata',
    iconType: 'shield',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 4,
    progressUnit: 'pilares concluídos',
    requirementHint: 'Complete Leis, Módulo de Respeito, 2 quizzes e 2 simulações interativas.'
  },
  {
    id: 'empatia_inabalavel',
    title: 'Farol do Acolhimento Escolar',
    subtitle: 'Realizou 8 ou mais escolhas de empatia e apoio nas simulações',
    description: 'Acumule pelo menos 8 decisões deliberadas de empatia, solidariedade e acolhimento nas simulações interativas.',
    unlockedDescription: 'Coração generoso! Em 8 momentos cruciais você estendeu a mão a quem mais precisava de apoio.',
    funnyQuote: '‘A gentileza é contagiosa: suas 8 atitudes empáticas transformaram o clima de cada cenário!’',
    funnySticker: '💖',
    category: 'empatia',
    tier: 'ouro',
    iconType: 'heart',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 8,
    progressUnit: 'escolhas de empatia',
    requirementHint: 'Faça 8 escolhas empáticas e acolhedoras nas simulações interativas.'
  },
  {
    id: 'mente_inabalavel',
    title: 'Santuário da Calma Interior',
    subtitle: 'Completou 6 ou mais sessões guiadas de respiração 4-7-8',
    description: 'Domine a autorregulação completando pelo menos 6 ciclos guiados de descompressão e respiração consciente.',
    unlockedDescription: 'Mente serena e centrada! Você desenvolveu um escudo de autocontrole capaz de acalmar qualquer momento de ansiedade.',
    funnyQuote: '‘Nem a maior turbulência tira o foco de quem aprendeu a respirar com consciência.’',
    funnySticker: '🧘',
    category: 'zen',
    tier: 'ouro',
    iconType: 'wind',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 6,
    progressUnit: 'sessões de calma',
    requirementHint: 'Pratique 6 sessões do exercício de respiração 4-7-8.'
  },
  {
    id: 'escudo_de_ouro_decisao',
    title: 'Muralha da Mediação Segura',
    subtitle: 'Realizou 8 ou mais decisões de segurança e prevenção nas simulações',
    description: 'Tome 8 decisões de prudência, acionando adultos de confiança e desescalando conflitos nas simulações interativas.',
    unlockedDescription: 'Proteção estratégica! Você evitou a violência e recorreu a canais seguros e responsáveis em 8 situações.',
    funnyQuote: '‘Coragem inteligente não é entrar na briga, é saber desarmar o conflito com segurança!’',
    funnySticker: '🛡️',
    category: 'escudo',
    tier: 'ouro',
    iconType: 'shield',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 8,
    progressUnit: 'escolhas de segurança',
    requirementHint: 'Faça 8 escolhas de proteção segura e mediação institucional nas simulações.'
  },
  {
    id: 'nivel_cinco_guardiao',
    title: 'Patente de Sentinela Veterano',
    subtitle: 'Alcançou o Nível 5 de Gamificação + 500 XP acumulados',
    description: 'Alcance o Nível 5 no perfil escolar acumulando pelo menos 500 pontos de experiência em atividades.',
    unlockedDescription: 'Patente conquistada! Seu engajamento contínuo te elevou ao Nível 5 com 500+ XP acumulados.',
    funnyQuote: '‘A constância forja os verdadeiros guardiões. Parabéns pela dedicação ao Sentinela!’',
    funnySticker: '🎖️',
    category: 'sabedoria',
    tier: 'ouro',
    iconType: 'award',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 5,
    progressUnit: 'nível alcançado',
    requirementHint: 'Evolua até o Nível 5 no sistema de níveis da plataforma.'
  },
  {
    id: 'conhecedor_total_quizzes',
    title: 'Gabaritador Implacável dos 5 Quizzes',
    subtitle: 'Atingiu 100% de aproveitamento em todos os 5 quizzes educativos',
    description: 'Gabarite com nota máxima (100% de acertos) todos os 5 quizzes temáticos disponíveis na plataforma.',
    unlockedDescription: 'Perfeição absoluta! 5 quizzes zerados com 100%. Você detém a enciclopédia completa da convivência ética.',
    funnyQuote: '‘Sem margem para dúvidas: 5 gabaritos perfeitos com maestria absoluta!’',
    funnySticker: '👑',
    category: 'sabedoria',
    tier: 'lendario',
    iconType: 'crown',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 5,
    progressUnit: 'quizzes com 100%',
    requirementHint: 'Obtenha nota máxima (100%) em todos os 5 quizzes educativos da plataforma.'
  },
  {
    id: 'arquiteto_do_destino',
    title: 'Arquiteto de Rotas & Desfechos',
    subtitle: 'Descobriu caminhos alternativos em pelo menos 5 simulações diferentes',
    description: 'Explore a fundo o multiverso escolar, descobrindo 2 ou mais finais em 5 cenários interativos distintos.',
    unlockedDescription: 'Pensamento analítico de ponta! Você testou diferentes ramificações em 5 simulações para compreender todas as consequências.',
    funnyQuote: '‘Cada escolha abre uma nova linha do tempo. Você domina todas as possibilidades!’',
    funnySticker: '🧭',
    category: 'detetive',
    tier: 'ouro',
    iconType: 'compass',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 5,
    progressUnit: 'cenários com 2+ finais',
    requirementHint: 'Descubra pelo menos 2 finais diferentes em 5 cenários de simulações.'
  },
  {
    id: 'explorador_segredos_sim',
    title: 'Caçador de Finais Secretos',
    subtitle: 'Descobriu pelo menos 2 desfechos secretos especiais nas simulações',
    description: 'Tome caminhos inusitados e descubra 2 finais secretos especiais escondidos nas histórias das simulações.',
    unlockedDescription: 'Detetive de elite! Você encontrou 2 rotas secretas ocultas nos cenários com perspicácia admirável.',
    funnyQuote: '‘Nem os roteiristas esperavam que você encontrasse todos esses caminhos secretos!’',
    funnySticker: '✨',
    category: 'detetive',
    tier: 'ouro',
    iconType: 'sparkles',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 2,
    progressUnit: 'finais secretos',
    requirementHint: 'Descubra 2 desfechos secretos especiais jogando as simulações interativas.'
  },
  {
    id: 'missao_cumprida_maratonista',
    title: 'Sentinela Comprometido',
    subtitle: 'Respondeu 60 ou mais questões de quizzes educativos',
    description: 'Acumule um total de 60 questões respondidas em quizzes ao longo da sua jornada no Sentinela.',
    unlockedDescription: 'Fôlego intelectual épico! 60 questões respondidas consolidam seu papel como líder de respeito escolar.',
    funnyQuote: '‘Mais de 60 decisões reflexivas respondidas: a sabedoria é fruto do treino constante.’',
    funnySticker: '🏃',
    category: 'sabedoria',
    tier: 'ouro',
    iconType: 'zap',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 60,
    progressUnit: 'questões respondidas',
    requirementHint: 'Responda a pelo menos 60 questões no total nos quizzes educativos.'
  },
  {
    id: 'harmonia_plena',
    title: 'Mestre da Autoregulação Emocional',
    subtitle: '10 sessões de respiração + Interação no chat de apoio emocional',
    description: 'Pratique o autocuidado com 10 sessões de respiração 4-7-8 e utilize o assistente socioemocional.',
    unlockedDescription: 'Mestre da serenidade! Seu autocuidado emocional reflete em uma mente clara e atitudes ponderadas.',
    funnyQuote: '‘Cuidar de si mesmo é o primeiro passo para conseguir proteger e acolher os outros.’',
    funnySticker: '🫁',
    category: 'zen',
    tier: 'ouro',
    iconType: 'wind',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 10,
    progressUnit: 'sessões zen completas',
    requirementHint: 'Realize 10 sessões de respiração 4-7-8 e converse no Apoio Emocional.'
  },
  {
    id: 'nivel_dez_comandante',
    title: 'Comandante da Cultura Escolar',
    subtitle: 'Alcançou o Nível 10 de Gamificação + 1.200 XP',
    description: 'Evolua seu perfil até o Nível 10 (Sentinela Veterano) e acumule pelo menos 1.200 XP na plataforma.',
    unlockedDescription: 'Nível 10 alcançado! Você agora ostenta a respeitada patente de Sentinela Veterano da comunidade escolar.',
    funnyQuote: '‘Uma década de níveis conquistada! Sua liderança ética inspira toda a escola.’',
    funnySticker: '⚡',
    category: 'sabedoria',
    tier: 'lendario',
    iconType: 'crown',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 10,
    progressUnit: 'nível alcançado',
    requirementHint: 'Alcance o Nível 10 de Gamificação no seu perfil escolar.'
  },
  {
    id: 'diplomata_da_paz',
    title: 'Diplomata Supremo da Convivência',
    subtitle: 'Concluiu todas as 10 simulações com pelo menos 15 escolhas de empatia',
    description: 'Zere todas as 10 simulações interativas acumulando pelo menos 15 escolhas de acolhimento e escuta ativa.',
    unlockedDescription: 'Diplomacia exemplar! Você venceu todas as 10 situações fictícias pautando suas atitudes na empatia máxima.',
    funnyQuote: '‘Construindo pontes onde outros cavam abismos: sua empatia salvou incontáveis recreios!’',
    funnySticker: '🤝',
    category: 'empatia',
    tier: 'lendario',
    iconType: 'handshake',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 15,
    progressUnit: 'escolhas de empatia em 10 sims',
    requirementHint: 'Complete todas as 10 simulações acumulando 15 escolhas empáticas.'
  },
  {
    id: 'guardiao_blindado_escola',
    title: 'Bastião Inviolável de Proteção',
    subtitle: '10 simulações concluídas + 15 escolhas de segurança preventiva',
    description: 'Complete todas as 10 simulações acumulando pelo menos 15 escolhas de proteção institucional segura.',
    unlockedDescription: 'Muralha de segurança! 10 cenários vencidos priorizando canais responsáveis e mediação sem violência.',
    funnyQuote: '‘Um escudo impenetrável contra a covardia: proteção com inteligência e responsabilidade.’',
    funnySticker: '🛡️',
    category: 'escudo',
    tier: 'lendario',
    iconType: 'shield',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 15,
    progressUnit: 'escolhas de segurança em 10 sims',
    requirementHint: 'Complete todas as 10 simulações acumulando 15 escolhas de segurança.'
  },
  {
    id: 'grande_colecionador',
    title: 'Grão-Mestre dos Distintivos',
    subtitle: 'Desbloqueou 25 ou mais conquistas na plataforma',
    description: 'Demonstre dedicação acima da média desbloqueando pelo menos 25 conquistas em sua galeria de honra.',
    unlockedDescription: 'Coleção lendária! 25 insígnias brilham no seu mural de honra. O Sentinela Escolar reconhece seu valor supremo.',
    funnyQuote: '‘25 medalhas reluzentes: um verdadeiro mestre colecionador da cultura de paz!’',
    funnySticker: '🏆',
    category: 'sabedoria',
    tier: 'lendario',
    iconType: 'trophy',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 25,
    progressUnit: 'conquistas desbloqueadas',
    requirementHint: 'Desbloqueie pelo menos 25 conquistas diferentes no sistema.'
  },
  {
    id: 'nivel_quinze_lorde',
    title: 'Lorde Sentinela Honorário',
    subtitle: 'Alcançou o Nível 15 de Gamificação + 2.000 XP',
    description: 'Alcance o prestigiado Nível 15 no perfil do Sentinela, acumulando mais de 2.000 pontos de experiência.',
    unlockedDescription: 'Nível 15 lendário! Poucos alcançam tamanha maestria e comprometimento com a ética e a paz.',
    funnyQuote: '‘No topo da sabedoria escolar: o título de Lorde Sentinela foi forjado com dedicação contínua.’',
    funnySticker: '💎',
    category: 'sabedoria',
    tier: 'lendario',
    iconType: 'crown',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 15,
    progressUnit: 'nível alcançado',
    requirementHint: 'Alcance o Nível 15 de Gamificação no seu perfil escolar.'
  },
  {
    id: 'mestre_absoluto_sentinela',
    title: 'Mestre Supremo da Cultura de Paz',
    subtitle: 'Nível 12+ • Todos os 5 Quizzes Gabaritados (100%) • Todas as 10 Simulações Zeradas • Leis e Respeito Lidos',
    description: 'Combine os requisitos de elite: Nível 12+, gabaritar todos os 5 quizzes com 100%, zerar todas as 10 simulações e concluir os módulos de Leis e Respeito.',
    unlockedDescription: 'Consagração máxima! Você dominou todos os pilares do Sentinela Escolar: quizzes, simulações, leis e convivência.',
    funnyQuote: '‘A perfeição existe na dedicação: você alcançou o patamar de Mestre Supremo do Sentinela!’',
    funnySticker: '👑',
    category: 'sabedoria',
    tier: 'lendario',
    iconType: 'crown',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 5,
    progressUnit: 'pilares mestres concluídos',
    requirementHint: 'Alcance Nível 12+, gabarite os 5 quizzes (100%), conclua as 10 simulações e leia Leis e Respeito.'
  },
  {
    id: 'lenda_viva_sentinela',
    title: 'Lenda Imortal do Sentinela Escolar',
    subtitle: 'Nível 18+ • 35+ Conquistas Desbloqueadas • 2.500+ XP • Domínio Total',
    description: 'O ápice supremo: alcance Nível 18+, acumule 2.500+ XP e desbloqueie pelo menos 35 conquistas em sua galeria.',
    unlockedDescription: 'Lenda Imortal! Você atingiu o ápice mais elevado de todo o Sentinela Escolar. Seu legado de respeito ecoará para sempre!',
    funnyQuote: '‘Você não é apenas um estudante na escola: você é a própria personificação da cultura de paz!’',
    funnySticker: '🌟',
    category: 'escudo',
    tier: 'lendario',
    iconType: 'sparkles',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 35,
    progressUnit: 'conquistas desbloqueadas',
    requirementHint: 'Alcance Nível 18+, 2.500+ XP e desbloqueie 35 conquistas diferentes.'
  },

  // =========================================================================
  // 🔒 CONQUISTAS SECRETAS (Ocultas inicialmente até serem desvendadas)
  // =========================================================================
  {
    id: 'secret_detetive_sentinela',
    title: 'Detetive do Sentinela',
    subtitle: 'Protocolo de Investigação & Proteção Desvendado',
    description: 'Conclua a sequência educativa de proteção: módulo de leis, análise de tipologias de bullying, quiz de segurança e simulação de proteção.',
    unlockedDescription: 'Parabéns, Detetive da Convivência! Você desvendou a rota de prevenção e domina as ferramentas essenciais de proteção escolar.',
    funnyQuote: '‘Elementar, meu caro Sentinela: com conhecimento e coragem, a covardia não tem vez.’',
    funnySticker: '🕵️',
    category: 'detetive',
    tier: 'prata',
    iconType: 'bot',
    isUnlocked: false,
    isSecret: true,
    xpReward: 50,
    secretRewardCosmeticId: 'badge_detetive_sentinela',
    currentProgress: 0,
    maxProgress: 4,
    progressUnit: 'etapas concluídas',
    requirementHint: 'Conquista secreta. Continue explorando a plataforma para descobrir.'
  },
  {
    id: 'secret_combo_conhecimento',
    title: 'Combo do Conhecimento',
    subtitle: 'Trilha Tripla de Aprendizado Contínuo',
    description: 'Execute um combo formativo de peso: conclua pelo menos 3 quizzes, o módulo de respeito e 3 simulações interativas.',
    unlockedDescription: 'Combo Lendário Descoberto! Sua sede de aprendizado conectou teoria e prática em uma sequência memorável.',
    funnyQuote: '‘Combo de Sabedoria 3x: mente afiada, postura firme e respeito em dobro!’',
    funnySticker: '⚡',
    category: 'sabedoria',
    tier: 'ouro',
    iconType: 'zap',
    isUnlocked: false,
    isSecret: true,
    xpReward: 75,
    secretRewardCosmeticId: 'icon_raio_sabedoria',
    currentProgress: 0,
    maxProgress: 3,
    progressUnit: 'pilares do combo',
    requirementHint: 'Conquista secreta. Continue explorando a plataforma para descobrir.'
  },
  {
    id: 'secret_mente_atenta',
    title: 'Mente Atenta',
    subtitle: 'Sequência de Foco e Discernimento Impecável',
    description: 'Acumule uma consistente sequência de 25 respostas em quizzes com alto índice de aproveitamento.',
    unlockedDescription: 'Mente Brilhante Descoberta! Sua atenção aos detalhes éticos e às condutas de respeito atingiu um padrão exemplar.',
    funnyQuote: '‘Neurônios em sincronia perfeita: você não apenas estuda, você compreende o impacto de cada escolha.’',
    funnySticker: '🧠',
    category: 'sabedoria',
    tier: 'ouro',
    iconType: 'target',
    isUnlocked: false,
    isSecret: true,
    xpReward: 75,
    secretRewardCosmeticId: 'effect_mente_atenta_aurora',
    currentProgress: 0,
    maxProgress: 25,
    progressUnit: 'questões certeiras',
    requirementHint: 'Conquista secreta. Continue explorando a plataforma para descobrir.'
  },
  {
    id: 'secret_codigo_secreto',
    title: 'Código Secreto',
    subtitle: 'Trindade de Ações da Cultura de Paz Decodificada',
    description: 'Desvende a tríade secreta: explore a matriz de tipos de bullying, pratique a respiração 4-7-8 e interaja no espaço de acolhimento emocional.',
    unlockedDescription: 'Código Secreto Decifrado! Você combinou conscientização, serenidade mental e empatia ativa.',
    funnyQuote: '‘Você encontrou o código oculto da paz escolar: serenidade na mente e empatia nas ações.’',
    funnySticker: '🔐',
    category: 'escudo',
    tier: 'ouro',
    iconType: 'sparkles',
    isUnlocked: false,
    isSecret: true,
    xpReward: 100,
    secretRewardCosmeticId: 'frame_codigo_secreto',
    currentProgress: 0,
    maxProgress: 3,
    progressUnit: 'chaves decodificadas',
    requirementHint: 'Conquista secreta. Continue explorando a plataforma para descobrir.'
  },
  {
    id: 'secret_sentinela_empatia',
    title: 'Sentinela da Empatia',
    subtitle: 'Trilha do Acolhimento e Convivência Fraterna',
    description: 'Conclua a trilha de empatia: módulo de respeito, 6 escolhas empáticas em situações interativas e apoio socioemocional.',
    unlockedDescription: 'Sentinela da Empatia Revelado! Seu coração acolhedor transforma corredores e salas em ambientes seguros para todos.',
    funnyQuote: '‘Empatia não é apenas uma palavra bonita: no seu dia a dia, ela é um escudo que protege quem precisa.’',
    funnySticker: '💜',
    category: 'empatia',
    tier: 'ouro',
    iconType: 'heart',
    isUnlocked: false,
    isSecret: true,
    xpReward: 75,
    secretRewardCosmeticId: 'frame_aura_empatia_secreta',
    currentProgress: 0,
    maxProgress: 3,
    progressUnit: 'marcos de empatia',
    requirementHint: 'Conquista secreta. Continue explorando a plataforma para descobrir.'
  },
  {
    id: 'secret_precisao_absoluta',
    title: 'Precisão Absoluta',
    subtitle: 'Excelência Total em Quizzes e Desfechos Exemplares',
    description: 'Gabarite com 100% de precisão pelo menos 2 quizzes educativos e alcance desfechos positivos em pelo menos 3 simulações.',
    unlockedDescription: 'Precisão Cirúrgica Reconhecida! Seu discernimento não deixa margem para dúvidas quando o assunto é ética e segurança.',
    funnyQuote: '‘Mira laser na verdade e no respeito: 100% de precisão e 0% de espaço para a injustiça.’',
    funnySticker: '🎯',
    category: 'sabedoria',
    tier: 'lendario',
    iconType: 'target',
    isUnlocked: false,
    isSecret: true,
    xpReward: 100,
    secretRewardCosmeticId: 'badge_precisao_absoluta',
    currentProgress: 0,
    maxProgress: 2,
    progressUnit: 'quizzes 100% + simulações',
    requirementHint: 'Conquista secreta. Continue explorando a plataforma para descobrir.'
  },
  {
    id: 'secret_explorador_noturno_areas',
    title: 'Explorador Oculto',
    subtitle: 'Navegador de Todas as Dimensões Pedagógicas',
    description: 'Visite e interaja com todas as áreas da plataforma: Legislação, Módulo de Respeito, Matriz de Bullying, Respiração Zen, Simulações e Chat de Apoio.',
    unlockedDescription: 'Explorador Supremo Descoberto! Você conhece cada detalhe, ferramenta e recurso do Sentinela Escolar como a palma da sua mão.',
    funnyQuote: '‘Não há canto inexplorado no mapa: você é o verdadeiro cartógrafo da cultura de paz!’',
    funnySticker: '🌙',
    category: 'detetive',
    tier: 'prata',
    iconType: 'compass',
    isUnlocked: false,
    isSecret: true,
    xpReward: 50,
    secretRewardCosmeticId: 'icon_bussola_astral',
    currentProgress: 0,
    maxProgress: 6,
    progressUnit: 'áreas integradas',
    requirementHint: 'Conquista secreta. Continue explorando a plataforma para descobrir.'
  },
  {
    id: 'secret_lenda_oculta',
    title: 'Lenda Oculta',
    subtitle: 'O Segredo Mais Nobre do Sentinela Escolar',
    description: 'Alcançou Nível 8+, desbloqueou 15+ insígnias, concluiu 4 quizzes e 5 simulações interativas.',
    unlockedDescription: 'Lenda Oculta Consagrada! Uma das conquistas mais raras de todo o ecossistema do Sentinela agora pertence a você.',
    funnyQuote: '‘Das sombras do anonimato surge a maior lenda de proteção e sabedoria que a escola já conheceu!’',
    funnySticker: '👑',
    category: 'escudo',
    tier: 'lendario',
    iconType: 'crown',
    isUnlocked: false,
    isSecret: true,
    xpReward: 200,
    secretRewardCosmeticId: 'title_lenda_oculta',
    currentProgress: 0,
    maxProgress: 4,
    progressUnit: 'grandes marcos',
    requirementHint: 'Conquista secreta. Continue explorando a plataforma para descobrir.'
  }
];

export const INITIAL_EDUCATIONAL_PROGRESS: EducationalActivityProgress = {
  viewedLaws: false,
  completedQuiz: false,
  exploredBullyingTypes: [],
  completedRespectModule: false,
  completedBreathingSession: false,
  breathingSessionsCount: 0,
  interactedWithChat: false,
  checkedOrCopiedProtocol: false,
  submittedOrViewedReport: false,
  accessedPlatformNightOrDay: true,
  quizzesProgress: {},
  totalQuestionsAnswered: 0,
  totalQuizzesCompleted: 0,
  
  // Simulações Interativas
  completedSimulations: [],
  exploredSimulationOutcomes: {},
  totalSimulationChoicesMade: 0,
  empathyChoicesCount: 0,
  safetyChoicesCount: 0,
  strategicExplorationsCount: 0,
  discoveredSecretOutcomesCount: 0
};

export const RANK_TIERS: RankTierInfo[] = [
  {
    levelNumber: 1,
    minAchievements: 0,
    title: '🛡️ Aprendiz da Cultura de Paz',
    badgeEmoji: '🌱',
    description: 'Iniciando a jornada com curiosidade e descobrindo seus direitos fundamentais.',
    color: 'text-emerald-900 bg-emerald-100 border-emerald-300'
  },
  {
    levelNumber: 2,
    minAchievements: 4,
    title: '⚡ Sentinela em Treinamento',
    badgeEmoji: '⚡',
    description: 'Já acolhe colegas isolados e pratica técnicas de respiração e respeito.',
    color: 'text-blue-900 bg-blue-100 border-blue-300'
  },
  {
    levelNumber: 3,
    minAchievements: 9,
    title: '🏆 Guardião da Convivência',
    badgeEmoji: '🏆',
    description: 'Argumentos éticos imbatíveis e atitudes ativas contra o bullying.',
    color: 'text-indigo-900 bg-indigo-100 border-indigo-300'
  },
  {
    levelNumber: 4,
    minAchievements: 15,
    title: '👑 Lorde Sentinela da Mediação',
    badgeEmoji: '👑',
    description: 'Mais sábio que enciclopédia e mestre na desescalada pacífica de conflitos.',
    color: 'text-purple-900 bg-purple-100 border-purple-300'
  },
  {
    levelNumber: 5,
    minAchievements: 22,
    title: '💎 Mestre Supremo do Bom Senso',
    badgeEmoji: '💎',
    description: 'Referência absoluta de empatia, sigilo e segurança no cotidiano escolar.',
    color: 'text-cyan-900 bg-cyan-100 border-cyan-300'
  },
  {
    levelNumber: 6,
    minAchievements: 29,
    title: '🔥 Senhor da Proteção & Respeito',
    badgeEmoji: '🔥',
    description: 'Estrategista de elite! Domina quizzes, leis e simulações com maestria.',
    color: 'text-rose-900 bg-rose-100 border-rose-300'
  },
  {
    levelNumber: 7,
    minAchievements: 36,
    title: '🌟 Lenda da Escola Sem Bullying',
    badgeEmoji: '🌟',
    description: 'Atingiu o patamar lendário de atitudes de paz, proteção e empatia.',
    color: 'text-amber-900 bg-amber-100 border-amber-300'
  },
  {
    levelNumber: 8,
    minAchievements: 43,
    title: '👑 Lenda Suprema do Sentinela',
    badgeEmoji: '👑',
    description: 'Platina total (43/43 conquistas)! O ápice supremo da cultura de paz escolar.',
    color: 'text-amber-950 bg-gradient-to-r from-amber-200 to-yellow-300 border-amber-400'
  }
];

export const getRankInfo = (unlockedCount: number): RankTierInfo => {
  for (let i = RANK_TIERS.length - 1; i >= 0; i--) {
    if (unlockedCount >= RANK_TIERS[i].minAchievements) {
      return RANK_TIERS[i];
    }
  }
  return RANK_TIERS[0];
};
