import { Achievement, EducationalActivityProgress } from './types';

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'conhecedor_direitos',
    title: 'Calouro Anti-Treta',
    subtitle: 'O primeiro passo para uma escola sem zueira pesada',
    description: 'Conclua seu primeiro quiz educativo sobre prevenção ao bullying e convivência escolar.',
    unlockedDescription: 'Parabéns! Você deu o pontapé inicial na cultura de paz. O primeiro passo foi dado com honra!',
    funnyQuote: '‘Zueira que machuca não é brincadeira, é falta de roteiro bom.’',
    funnySticker: '🎓',
    category: 'sabedoria',
    tier: 'bronze',
    iconType: 'trophy',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 1,
    progressUnit: 'quiz concluído',
    requirementHint: 'Conclua qualquer 1 quiz na aba "Quiz Anti-Bullying".'
  },
  {
    id: 'aliado_escola_segura',
    title: 'Trio Parada Firme da Paz',
    subtitle: 'Três quizzes no bolso e tolerância zero com covardia',
    description: 'Amplie seus conhecimentos completando 3 quizzes educativos sobre respeito e segurança.',
    unlockedDescription: 'Incrível! Três quizzes finalizados. Você já pode dar aula de bom senso no intervalo!',
    funnyQuote: '‘Três vitórias seguidas. Nem o Wi-Fi da escola é tão estável quanto sua determinação.’',
    funnySticker: '🛡️',
    category: 'sabedoria',
    tier: 'prata',
    iconType: 'shield',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 3,
    progressUnit: 'quizzes concluídos',
    requirementHint: 'Conclua 3 quizzes diferentes na área "Quiz Anti-Bullying".'
  },
  {
    id: 'especialista_respeito',
    title: 'Cérebro Galáctico do Respeito',
    subtitle: 'Neurônios brilhando mais que a tela do celular no escuro',
    description: 'Demonstre domínio e alcance pelo menos 80% de aproveitamento em 3 quizzes educativos.',
    unlockedDescription: 'Uau! Aproveitamento de elite (≥80%) em 3 quizzes. Seus argumentos contra o preconceito são imbatíveis!',
    funnyQuote: '‘QI de empatia acima de 9.000! Albert Einstein ficaria orgulhoso dessa mente brilhante.’',
    funnySticker: '🧠',
    category: 'sabedoria',
    tier: 'ouro',
    iconType: 'sparkles',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 3,
    progressUnit: 'quizzes com ≥ 80%',
    requirementHint: 'Acerte pelo menos 4 de 5 perguntas (80%) em 3 quizzes educativos.'
  },
  {
    id: 'protetor_comunidade',
    title: 'Gabaritador Lendário de Bom Senso',
    subtitle: 'Zerou todos os 5 quizzes da jornada educativa',
    description: 'Conclua todos os 5 quizzes disponíveis na jornada educativa do Sentinela Escolar.',
    unlockedDescription: 'Jornada zerada com sucesso! Você completou todos os quizzes. O Ministério do Respeito te aplaude de pé!',
    funnyQuote: '‘Platinou o quiz! Agora você tem imunidade diplomática contra fofocas e picuinhas.’',
    funnySticker: '👑',
    category: 'sabedoria',
    tier: 'lendario',
    iconType: 'crown',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 5,
    progressUnit: 'quizzes concluídos',
    requirementHint: 'Complete todos os 5 quizzes educativos disponíveis na plataforma.'
  },
  {
    id: 'gabarito_perfeito',
    title: 'Oráculo do 100% Sem Chute',
    subtitle: 'Acertou 5 de 5 perguntas de primeira. Aqui é pura sabedoria!',
    description: 'Alcance pontuação máxima perfeita (100%) em qualquer um dos quizzes educativos.',
    unlockedDescription: 'Perfeição pura! Você acertou todas as perguntas de um quiz sem errar uma única vírgula.',
    funnyQuote: '‘Não foi uni-duni-tê: foi estudo, empatia e mira laser na alternativa certa!’',
    funnySticker: '🎯',
    category: 'sabedoria',
    tier: 'ouro',
    iconType: 'target',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 1,
    progressUnit: 'quiz com 100%',
    requirementHint: 'Acerte 5 de 5 perguntas (100%) em qualquer quiz educativo.'
  },
  {
    id: 'speedrunner_sabedoria',
    title: 'Detetive Cibernético Anti-Fake',
    subtitle: 'Firewall moral ativado contra o cyberbullying',
    description: 'Conclua o Quiz de Cyberbullying e Segurança Digital com aproveitamento igual ou superior a 80%.',
    unlockedDescription: 'Mestre da internet segura! Você sabe como proteger provas digitais e barrar o ódio online.',
    funnyQuote: '‘Nem os trolls da web mais experientes conseguem passar pelo seu escudo de bom senso.’',
    funnySticker: '🕵️‍♂️',
    category: 'detetive',
    tier: 'prata',
    iconType: 'bot',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 1,
    progressUnit: 'cyber quiz concluído',
    requirementHint: 'Conclua o quiz "Cyberbullying & Segurança Digital" com 80%+ de acerto.'
  },
  {
    id: 'enciclopedia_viva',
    title: 'Maratonista de Neurônios',
    subtitle: 'Respondeu 20 perguntas em quizzes educativos',
    description: 'Demonstre consistência acumulando pelo menos 20 respostas respondidas nos quizzes.',
    unlockedDescription: 'Que fôlego intelectual! Você já respondeu mais de 20 questões sobre convivência ética e segurança.',
    funnyQuote: '‘Mais focado que estudante em semana de prova e com coração 100% no lugar certo.’',
    funnySticker: '🏃‍♂️',
    category: 'sabedoria',
    tier: 'ouro',
    iconType: 'zap',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 20,
    progressUnit: 'questões respondidas',
    requirementHint: 'Responda a pelo menos 20 questões no total nos quizzes educativos.'
  },
  {
    id: 'explorador_matriz',
    title: 'Curioso Nível Hard: 7 em 1',
    subtitle: 'Explorou todas as 7 categorias da Matriz de Bullying',
    description: 'Estude todos os 7 tipos de bullying (verbal, físico, cyber, moral, social, material e sexual).',
    unlockedDescription: 'Explorador completo! Você conheceu os detalhes, sinais e formas de reação de todas as 7 categorias.',
    funnyQuote: '‘Você manja mais de prevenção escolar do que o fiscal de corredor mais antigo!’',
    funnySticker: '🔍',
    category: 'detetive',
    tier: 'prata',
    iconType: 'compass',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 7,
    progressUnit: 'categorias exploradas',
    requirementHint: 'Clique e explore todas as 7 abas na Matriz dos 7 Tipos de Bullying.'
  },
  {
    id: 'advogado_do_bem',
    title: 'Doutor em Não-Vacilo (Vade Mecum Escolar)',
    subtitle: 'Leu a Lei 13.185/2015 e o Artigo 146-A da Lei 14.811',
    description: 'Acesse o módulo de Legislação e conheça seus direitos e a proteção legal contra a intimidação.',
    unlockedDescription: 'Conhecedor das Leis! Se alguém tentar intimidar, você cita a Lei 14.811 com postura de respeito.',
    funnyQuote: '‘Código Penal na ponta da língua e empatia no coração: ninguém te passa a perna.’',
    funnySticker: '⚖️',
    category: 'detetive',
    tier: 'bronze',
    iconType: 'scale',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 1,
    progressUnit: 'módulo de leis',
    requirementHint: 'Leia o módulo "Leis e Proteção Legal" e clique em "Marcar como Lido".'
  },
  {
    id: 'coracao_de_ouro',
    title: 'Embaixador da Empatia Master',
    subtitle: 'Superpoder oficial: nunca deixar ninguém sozinho no recreio',
    description: 'Conclua a leitura e reflexão do Módulo de Respeito, Empatia e Convivência Escolar.',
    unlockedDescription: 'Coração gigante! Você compreendeu a importância de acolher colegas e ser uma testemunha ativa do bem.',
    funnyQuote: '‘Pequenos gestos de gentileza salvam o dia de alguém sem você nem perceber.’',
    funnySticker: '💖',
    category: 'empatia',
    tier: 'bronze',
    iconType: 'handshake',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 1,
    progressUnit: 'módulo de respeito',
    requirementHint: 'Clique em "Marcar como Lido e Compreendido" no banner de Respeito e Empatia.'
  },
  {
    id: 'campeao_inclusao',
    title: 'Radar Anti-Exclusão Social',
    subtitle: 'Para você, todo mundo tem lugar garantido no time',
    description: 'Conclua o Quiz de Empatia e Convivência Escolar com aproveitamento excelente (≥80%).',
    unlockedDescription: 'Craque do acolhimento! Você sabe exatamente como transformar panelinhas tóxicas em pontes de amizade.',
    funnyQuote: '‘Se a vida fosse um jogo cooperativo, você seria aquele player que revive o time inteiro!’',
    funnySticker: '🤝',
    category: 'empatia',
    tier: 'prata',
    iconType: 'heart',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 1,
    progressUnit: 'quiz de empatia',
    requirementHint: 'Conclua o quiz "Empatia & Convivência" com 80%+ de acertos.'
  },
  {
    id: 'mente_tranquila',
    title: 'Monge Zen Anti-Estresse',
    subtitle: 'Inspirou 4, segurou 7, soltou 8. O caos sumiu!',
    description: 'Realize uma sessão de respiração guiada 4-7-8 no botão "Acalmar" ou no Apoio Emocional.',
    unlockedDescription: 'Paz restaurada! Você praticou a técnica comprovada de descompressão e oxigenou a mente.',
    funnyQuote: '‘Respirou fundo e o estresse evaporou igual água em frigideira quente. Namastê!’',
    funnySticker: '🧘‍♂️',
    category: 'zen',
    tier: 'bronze',
    iconType: 'wind',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 1,
    progressUnit: 'sessão de respiração',
    requirementHint: 'Clique no botão "Acalmar" (no topo) ou use o exercício no Apoio Emocional.'
  },
  {
    id: 'mestre_zen',
    title: 'Pulmão de Aço da Serenidade',
    subtitle: 'Três sessões de descompressão concluídas com maestria',
    description: 'Complete 3 sessões completas de respiração e relaxamento para manter a tranquilidade.',
    unlockedDescription: 'Nível mestre de serenidade! Nem prova surpresa com chamada oral abala a sua paz interior.',
    funnyQuote: '‘Sua calma interior é tão sólida que até monges tibetanos pediriam dicas de meditação.’',
    funnySticker: '🫁',
    category: 'zen',
    tier: 'prata',
    iconType: 'wind',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 3,
    progressUnit: 'sessões de calma',
    requirementHint: 'Pratique 3 sessões do exercício de respiração 4-7-8.'
  },
  {
    id: 'desabafo_seguro',
    title: 'Coração Leve, Mente Clara',
    subtitle: 'Acolhimento com privacidade e escuta atenta',
    description: 'Abra a Central de Apoio Emocional e converse com o assistente confidencial de apoio.',
    unlockedDescription: 'Conversar alivia a alma! Você acessou um espaço seguro para organizar ideias e emoções.',
    funnyQuote: '‘Guardar tudo pra si é pesado demais. Desabafar com segurança é pura sabedoria.’',
    funnySticker: '💬',
    category: 'empatia',
    tier: 'bronze',
    iconType: 'smile',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 1,
    progressUnit: 'conversa de apoio',
    requirementHint: 'Envie uma mensagem ou abra o chat na aba "Apoio Emocional".'
  },
  {
    id: 'guardiao_digital',
    title: 'Agente Secreto do Protocolo',
    subtitle: 'Segurança máxima: chave de acompanhamento 100% anônima',
    description: 'Consulte o andamento de um protocolo confidencial ou copie seu código com segurança.',
    unlockedDescription: 'Agente da transparência! Você aprendeu a acompanhar desfechos com total privacidade.',
    funnyQuote: '‘Nem a NASA tem um código tão bem guardado quanto o seu protocolo seguro!’',
    funnySticker: '🔐',
    category: 'escudo',
    tier: 'prata',
    iconType: 'eye',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 1,
    progressUnit: 'consulta realizada',
    requirementHint: 'Consulte um protocolo na aba "Acompanhar Protocolo".'
  },
  {
    id: 'radar_antizueira',
    title: 'Escudo Guardião Ativado',
    subtitle: 'Atuando com responsabilidade para uma escola melhor',
    description: 'Envie ou consulte um relato seguro contra o bullying, ajudando a proteger o ambiente escolar.',
    unlockedDescription: 'Protetor em ação! Sua atitude cidadã ajuda a quebrar o ciclo de silêncio e impunidade.',
    funnyQuote: '‘Herói da vida real não usa capa, usa bom senso e canais éticos de proteção.’',
    funnySticker: '🛡️',
    category: 'escudo',
    tier: 'bronze',
    iconType: 'shield',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 1,
    progressUnit: 'ação de proteção',
    requirementHint: 'Envie um relato responsável ou consulte seu código anônimo.'
  },
  {
    id: 'sentinela_noturno',
    title: 'Sentinela Noturno da Paz',
    subtitle: 'A cultura do respeito não tira folga nem quando o sol se põe',
    description: 'Estude ou acesse a plataforma Sentinela Escolar para fortalecer a convivência pacífica.',
    unlockedDescription: 'Dedicação comprovada! Você está sempre pronto para aprender e disseminar o respeito.',
    funnyQuote: '‘A coruja da sabedoria passou por aqui e deixou um distintivo especial pra você!’',
    funnySticker: '🦉',
    category: 'escudo',
    tier: 'bronze',
    iconType: 'award',
    isUnlocked: false,
    currentProgress: 1,
    maxProgress: 1,
    progressUnit: 'acesso à plataforma',
    requirementHint: 'Explore os módulos educativos ou ferramentas do Sentinela Escolar.'
  },
  {
    id: 'colecionador_supremo',
    title: 'Lorde Supremo dos Distintivos',
    subtitle: 'Desbloqueou 10 ou mais conquistas na plataforma',
    description: 'Demonstre dedicação máxima desbloqueando pelo menos 10 conquistas educativas no Sentinela.',
    unlockedDescription: 'Lenda absoluta! Você atingiu a marca de 10 conquistas. Sua dedicação à cultura de paz é exemplar!',
    funnyQuote: '‘Você praticamente platinou o Sentinela Escolar! A diretoria deveria te dar uma medalha de ouro.’',
    funnySticker: '🏆',
    category: 'sabedoria',
    tier: 'lendario',
    iconType: 'trophy',
    isUnlocked: false,
    currentProgress: 0,
    maxProgress: 10,
    progressUnit: 'conquistas desbloqueadas',
    requirementHint: 'Desbloqueie pelo menos 10 conquistas diferentes no sistema.'
  }
];

export const INITIAL_EDUCATIONAL_PROGRESS: EducationalActivityProgress = {
  viewedLaws: false,
  completedQuiz: false,
  exploredBullyingTypes: [],
  completedRespectModule: false,
  completedBreathingSession: false,
  breathingSessionsCount: 0,
  interactedWithChat: false,
  checkedOrCopiedProtocol: false,
  submittedOrViewedReport: false,
  accessedPlatformNightOrDay: true,
  quizzesProgress: {},
  totalQuestionsAnswered: 0,
  totalQuizzesCompleted: 0
};
